name: Code formatter lua with stylua

on:
  workflow_call:
    inputs:
      all-changed-files-list:
        required: true
        type: string
      any-changed-files-list:
        required: true
        type: string
jobs:
  formatter-lua:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          
      - name: Download and save the script
        if: ${{ inputs.any-changed-files-list == 'true' }}
        run: curl -f -o script.js https://raw.githubusercontent.com/CommunityRP-FiveM-Server/public_test/main/.github/actions/script.js

      - name: Install replacer-lib
        if: ${{ inputs.any-changed-files-list == 'true' }}
        run: npm install replace-in-file

      - name: Run replace script
        if: ${{ inputs.any-changed-files-list == 'true' }}
        run: node script.js do
        
      - name: Install stylua and run formatter
        if: ${{ inputs.any-changed-files-list == 'true' }}
        uses: JohnnyMorganz/stylua-action@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: v0.19.1
          args: -- ${{ inputs.all-changed-files-list }}

      - name: Run undo script
        if: ${{ inputs.any-changed-files-list == 'true' }}
        run: node script.js undo
