name: Code formatter web files with prettier

on:
  workflow_call:
    inputs:
      all-changed-files-list:
        required: true
        type: string
      any-changed-files-list:
        required: true
        type: string
jobs:
  formatter:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          
      - name: Get changed web file extensions
        if: ${{ inputs.any-changed-files-list == 'true' }}
        id: getext
        run: |
          import os
          files = '${{ inputs.all-changed-files-list }}'.split()
          extensions = set('*' + os.path.splitext(file)[1] for file in files)
          with open(os.getenv('GITHUB_ENV'), 'a') as f:
            f.write(f"CHANGED_EXTENSIONS={' '.join(extensions)}\n")
        shell: python
        
      - name: Format changed files with Prettier
        if: ${{ inputs.any-changed-files-list == 'true' }}
        run: | 
            npm install --save-dev prettier && npx prettier --write ${{ inputs.all-changed-files-list }}

      - name: Update repo before push
        run: |
          git pull
          
      - name: Commit changed files and push current branch
        if: ${{ inputs.any-changed-files-list == 'true' }}
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_user_name: ESX GITHUB ACTIONS BOT
          commit_user_email: esx-github-actions-bot@users.noreply.github.com
          commit_message: :art:Code formatted in ${{ env.CHANGED_EXTENSIONS }} files
          file_pattern: ${{ env.CHANGED_EXTENSIONS }}
          status_options: '--untracked-files=no'
            
