name: Code formatter web files with prettier

on:
  workflow_call:
    inputs:
      all-changed-files-list:
        required: true
        type: string
      any-changed-files-list:
        required: true
        type: string
jobs:
  formatter:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          
      - name: Get changed web file extensions
        if: steps.changed-files-web.outputs.any_changed == 'true'
        id: getext
        run: |
          import os
          files = '${{ steps.changed-files-web.outputs.all_changed_files }}'.split()
          extensions = set('*' + os.path.splitext(file)[1] for file in files)
          with open(os.getenv('GITHUB_ENV'), 'a') as f:
            f.write(f"CHANGED_EXTENSIONS={' '.join(extensions)}\n")
        shell: python
        
      - name: Format changed files with Prettier
        if: steps.changed-files-web.outputs.any_changed == 'true'
        run: | 
            npm install --save-dev prettier && npx prettier --write ${{ steps.changed-files-web.outputs.all_changed_files }}  
            
